/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaboratoryRouteImport } from './routes/laboratory'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppointmentRouteImport } from './routes/appointment'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddPatientRouteImport } from './routes/add-patient'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoryRoute = LaboratoryRouteImport.update({
  id: '/laboratory',
  path: '/laboratory',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentRoute = AppointmentRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPatientRoute = AddPatientRouteImport.update({
  id: '/add-patient',
  path: '/add-patient',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-patient': typeof AddPatientRoute
  '/admin': typeof AdminRoute
  '/appointment': typeof AppointmentRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/doctor': typeof DoctorRoute
  '/doctors': typeof DoctorsRoute
  '/laboratory': typeof LaboratoryRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-patient': typeof AddPatientRoute
  '/admin': typeof AdminRoute
  '/appointment': typeof AppointmentRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/doctor': typeof DoctorRoute
  '/doctors': typeof DoctorsRoute
  '/laboratory': typeof LaboratoryRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-patient': typeof AddPatientRoute
  '/admin': typeof AdminRoute
  '/appointment': typeof AppointmentRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/doctor': typeof DoctorRoute
  '/doctors': typeof DoctorsRoute
  '/laboratory': typeof LaboratoryRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/add-patient'
    | '/admin'
    | '/appointment'
    | '/contact'
    | '/departments'
    | '/doctor'
    | '/doctors'
    | '/laboratory'
    | '/login'
    | '/patient'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/add-patient'
    | '/admin'
    | '/appointment'
    | '/contact'
    | '/departments'
    | '/doctor'
    | '/doctors'
    | '/laboratory'
    | '/login'
    | '/patient'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/add-patient'
    | '/admin'
    | '/appointment'
    | '/contact'
    | '/departments'
    | '/doctor'
    | '/doctors'
    | '/laboratory'
    | '/login'
    | '/patient'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddPatientRoute: typeof AddPatientRoute
  AdminRoute: typeof AdminRoute
  AppointmentRoute: typeof AppointmentRoute
  ContactRoute: typeof ContactRoute
  DepartmentsRoute: typeof DepartmentsRoute
  DoctorRoute: typeof DoctorRoute
  DoctorsRoute: typeof DoctorsRoute
  LaboratoryRoute: typeof LaboratoryRoute
  LoginRoute: typeof LoginRoute
  PatientRoute: typeof PatientRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratory': {
      id: '/laboratory'
      path: '/laboratory'
      fullPath: '/laboratory'
      preLoaderRoute: typeof LaboratoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment': {
      id: '/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-patient': {
      id: '/add-patient'
      path: '/add-patient'
      fullPath: '/add-patient'
      preLoaderRoute: typeof AddPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddPatientRoute: AddPatientRoute,
  AdminRoute: AdminRoute,
  AppointmentRoute: AppointmentRoute,
  ContactRoute: ContactRoute,
  DepartmentsRoute: DepartmentsRoute,
  DoctorRoute: DoctorRoute,
  DoctorsRoute: DoctorsRoute,
  LaboratoryRoute: LaboratoryRoute,
  LoginRoute: LoginRoute,
  PatientRoute: PatientRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
